
/*
    - LunaKit Info Viewer Window -

    This window displays general information about various parts of the game
    Uses categories

    https://github.com/Amethyst-szs/smo-lunakit/wiki#info-viewer
*/

#pragma once

#include "imgui.h"

#include "program/devgui/windows/WindowBase.h"

#include "program/devgui/categories/CategoryBase.h"
#include "program/devgui/categories/info/CategoryInfSequence.h"
#include "program/devgui/categories/info/CategoryInfScene.h"
#include "program/devgui/categories/info/CategoryInfPlayer.h"

__attribute__((used)) static const char* presetsWindowName = "GPresets";

namespace al {
    class SkyParam;
}

struct GraphicsPresetSet {
    bool mIsOverride = false;
    bool mIsOverrideSky = false;
    int mTotalPreset = -1;
    int mTotalCubemap = -1;
    int mTotalSky = -1;
    const char *mPreset = "Default";
    const char *mCubemap = "LightingPlayerMoonGetStage";
    const char *mSky = "null";
    int mScenario = 1;
};

class WindowPresets : public WindowBase {
public:
    WindowPresets(DevGuiManager* parent, const char* winName, bool isActiveByDefault);

    void updateWin() override;
    bool tryUpdateWinDisplay() override;

private:
    void drawPresetDropdown(const char* header, const int totalOptions, const char** output);
    void drawDropdown(const char* header, const char* options[], const char* translatedOptions[], const int totalOptions, const char** output);

    ImGuiComboFlags mComboFlags;
    bool mIsReloadScene = false;
};

__attribute__((used)) static const char* presetList[] = {
    "3DEditor確認用の白い空間",
    "Default",
    "EXキャプチャーパレード",
    "EXジッパー(サブムーンエリア)",
    "EXジッパー(鍵取得後)",
    "EXジッパー",
    "EX帽子回転迷路",
    "EX建物回転",
    "EX棒のぼり",
    "EX水中土管",
    "EX汎用暗空",
    "EX異次元空(グレイッシュ)",
    "EX異次元空(シャンパンゴールド)",
    "EX異次元空(ダルトーン)",
    "EX異次元空(パステル)",
    "EX異次元空(明るい)",
    "EX異次元空(暗い空)",
    "EX異次元空(青い空間)",
    "クッパ戦Lv3(クリア後)",
    "ショップ(暖色)",
    "スタッフロール",
    "スロット部屋",
    "デモエンディング月面(飛び立ちジャンプ)",
    "デモエンディング月面",
    "デモエンディング月面飛び立ち",
    "デモオープニング",
    "デモキャップと出会い(クッパ)",
    "デモクッパの攻撃ホーム転落(ティアラアップ)",
    "デモクッパの攻撃ホーム転落(雲昼空)",
    "デモクッパキャプチャー",
    "デモクッパ戦艦発見(ホーム内部カット)",
    "デモクッパ戦艦発見(雲昼空)",
    "デモダイバー白空間",
    "デモホーム移動(帰り)",
    "デモワールドワープ",
    "デモワールド移動(ホーム内部)",
    "デモワールド移動(夕方)",
    "デモワールド移動(夜)",
    "デモワールド移動(宇宙)",
    "デモワールド移動(嵐)",
    "デモワールド移動(昼)",
    "デモワールド移動(曇り)",
    "デモワールド移動(月と地球の間)",
    "デモ初キャプチャ(塔内部後半)",
    "デモ初キャプチャー蛙の記憶(塔内部)",
    "デモ初キャプチャー蛙の記憶",
    "デモ滝ワールドへ電線移動",
    "デモ砂漠ボスナックル",
    "デモ襲撃ボス攻撃",
    "ピーチ(64中庭)",
    "ピーチEXヨッシークラウド",
    "ピーチEX福笑い",
    "ピーチワールド(ピーチ城広間)",
    "ピーチワールド(小部屋ボス入口)",
    "ピーチワールド(屋外)",
    "ピーチワールド(屋外コンプリート用)",
    "ピーチ城コスチューム部屋",
    "ピーチ城ワールドEX高難度ドット",
    "プレイガイド",
    "プレイヤーライト(クローゼット) ",
    "プレイヤーライト(ショップ) ",
    "プレイヤーライト(ポーズ) ",
    "プレイヤーライト(ムーンゲット) ",
    "プログラマ確認用(TREX実験)",
    "プログラマ確認用",
    "プログラマ確認用その2",
    "プログラマ確認用その3",
    "プログラマ確認用その4",
    "プログラマ確認用その5",
    "プログラマ確認用その6",
    "プログラマ確認用その7",
    "ヘルプ撮影用空間",
    "ベース環境(夜)",
    "ベース環境2D洞窟",
    "ベース環境：夜",
    "ベース環境：室内暖色",
    "ホーム内部",
    "ワールドマップ",
    "墜落EXイモムーポイズン",
    "墜落EXジャンゴ",
    "墜落夜空",
    "多面図撮影用",
    "帽子EX押し出しブロック",
    "帽子EX転がり",
    "帽子の里(塔内部)",
    "帽子の里EXカエルの探し物",
    "帽子の里EX毒波",
    "帽子の里満月",
    "帽子満月空(塔の後ろ)",
    "平原EXリフト2D",
    "平原EX帽子出現足場(デフォルメ)",
    "平原EX帽子出現足場",
    "平原EX恐竜とポップン",
    "平原青空(E3PV恐竜デモ)",
    "平原青空(制作テスト用)",
    "平原青空",
    "月EXキャプチャーパレード",
    "月EX月重力アスレチック",
    "月キャプチャパレード(ThankYouエリア)",
    "月キャプチャパレード(森)",
    "月キャプチャパレード(溶岩)",
    "月キャプチャパレード(滝)",
    "月キャプチャパレード(真ベース)",
    "月キャプチャパレード(砂)",
    "月キャプチャパレード(都市)",
    "月キャプチャパレード",
    "月クッパ戦(クリア後)",
    "月クッパ戦(１ダメージ後)",
    "月クッパ戦(２ダメージ後)",
    "月クッパ戦",
    "月クッパ戦Lv3(クリア後)",
    "月クッパ戦Lv3(１ダメージ後)",
    "月クッパ戦Lv3(２ダメージ後)",
    "月クッパ戦Lv3",
    "月宇宙空(GK４連戦)",
    "月宇宙空(逆光)",
    "月宇宙空",
    "月宇宙空真キャプチャパレード",
    "月宝箱部屋",
    "月崩落(中間エリア)",
    "月崩落(最終エリア)",
    "月崩落",
    "月教会内部",
    "月裏EXギャラクシー2",
    "月裏EXシューティングシティー",
    "月裏EXバイク",
    "月裏EXポイズンパックンEX",
    "月裏EX浮き沈み",
    "月裏GK4連戦ボス部屋",
    "月裏真キャプチャ星雲宇宙空",
    "月裏雲海",
    "森(樹海エリア)",
    "森EXキラーロード",
    "森EXシューティングエレベーター",
    "森EXセノビー雲ボーナス",
    "森EXポイズンパックン",
    "森EXレール生成",
    "森EX羊飼い",
    "森EX霧の山",
    "森アスレチック報酬部屋",
    "森コスチューム部屋",
    "森タワー内部",
    "森曇り空(トンネル内)",
    "森曇り空(森エリア)",
    "森曇り空(機械エリア)",
    "森樹海宝箱部屋",
    "森青空(トンネル内)",
    "森青空(ブロックボス)",
    "森青空(ボス)",
    "森青空(森エリア)",
    "森青空(機械エリア)",
    "森青空",
    "森青空花咲き後(トンネル内)",
    "森青空花咲き後(森エリア)",
    "森青空花咲き後(機械エリア)",
    "汎用EXキューブ(暗い)",
    "海(コスチューム部屋)",
    "海(小部屋)",
    "海(振動小部屋)",
    "海(水中小部屋)",
    "海EXコソコソくん部屋",
    "海EXセノビータワー",
    "海EXホウスイ谷(谷底エリア)",
    "海EXホウスイ谷",
    "海EX帽子回転トゲゾー",
    "海EX雲海",
    "海夕焼け(水中なのでゴッドレイなし)",
    "海夕焼け",
    "海天気雨空(ボス再戦)",
    "海洞窟",
    "海青空",
    "海青空EX反射爆弾",
    "湖EXトランポリンぶら下がり",
    "湖カエル毒沼",
    "湖ゴトゴトン",
    "湖夜(水中)",
    "湖夜",
    "湖昼",
    "溶岩EXガブゾウロック",
    "溶岩EXクロック",
    "溶岩EXフォーク",
    "溶岩EXペチョの細道",
    "溶岩EX共通",
    "溶岩EX掘削",
    "溶岩EX浮き沈み",
    "溶岩EX溶岩クルーズ",
    "溶岩EX金網リフト",
    "溶岩コスチューム部屋",
    "溶岩デモシナリオ1終了",
    "溶岩噴火中",
    "溶岩噴火前(影の向き調整用垂直ライト)",
    "溶岩噴火前",
    "溶岩噴火最中(影の向き調整用垂直ライト)",
    "溶岩噴火最中",
    "溶岩宝箱部屋",
    "溶岩洞窟",
    "滝EX横向き上昇気流",
    "砂EXホウスイ水路",
    "砂EX振動小部屋",
    "砂漠EXキラー",
    "砂漠EXスフィンクスラン",
    "砂漠EXメガネー",
    "砂漠EXメガネーリフト",
    "砂漠コスチューム部屋",
    "砂漠ピラミッド内部",
    "砂漠ボスナックル",
    "砂漠ボスナックルOmitDof",
    "砂漠夜空",
    "砂漠昼",
    "砂漠昼逆光(2016_10映像用)",
    "砂漠昼逆光",
    "砂漠曇り",
    "砂漠朝",
    "砂漠氷地下",
    "砂漠黄金部屋",
    "空EXツックンクライム",
    "空EXツックン回転",
    "空EXパタカロン",
    "空EX地蔵",
    "空EX雲ボーナス",
    "空夕焼け空",
    "空夜空(クリア後)",
    "空夜空(クリア後月の石解放デモ)",
    "空夜空",
    "空屏風部屋",
    "空曇り空(月の石解放デモ)",
    "空曇り空",
    "空青空",
    "空黄金部屋",
    "襲撃EXドットタワー",
    "襲撃EXブルラン",
    "襲撃嵐空(クリア後ゴッドレイ消し)",
    "襲撃嵐空(ハイコントラスト)",
    "襲撃嵐空(月の石デモのゴッドレイ消し)",
    "襲撃嵐空(氷再戦)",
    "襲撃嵐空(氷再戦ゴッドレイオフ)",
    "襲撃嵐空(演出重視)",
    "襲撃嵐空",
    "都市EX2D試写室",
    "都市EXぶらさがり",
    "都市EXグラグラ鉄骨",
    "都市EXシューティングシティー",
    "都市EXバイク",
    "都市EX恐竜とバイク",
    "都市EX棒のぼり",
    "都市EX群衆",
    "都市EX電線",
    "都市EX音符部屋",
    "都市コンサート会場",
    "都市ビル内部(昼)",
    "都市ビル内部夜",
    "都市ビル内部昼",
    "都市ラジコン部屋",
    "都市地下工場(コアエリア)",
    "都市地下工場(回転足場エリア)",
    "都市地下工場(通路エリア)",
    "都市夜セレモニーライブ(ムーンゲット)",
    "都市夜セレモニーライブ",
    "都市夜空(スタート地点)",
    "都市夜空",
    "都市夜空明るめ(地面付近2Dエリア)",
    "都市夜空明るめ",
    "都市昼雨空",
    "都市青空(DiverデモＡ)",
    "都市青空(Diver静止画用)",
    "都市青空(スタート地点：自動露出無し)",
    "都市青空(プレイヤーライト検証)",
    "都市青空(メインビジュアル)",
    "都市青空(写真テスト)",
    "都市青空",
    "雪EXアイスウォーカー",
    "雪EXキラーレール生成",
    "雪EXドット円塔",
    "雪EXビューゴーパズル",
    "雪EX氷ダッシュ",
    "雪EX氷水ブロック",
    "雪サーキット撮影用",
    "雪夜空(サーキット)",
    "雪室内(レース入場口)",
    "雪室内",
    "雪曇り空(サーキット)",
    "雪曇り空(濃霧)",
    "雪曇り空(ＧＫ戦)",
    "雪雲ボーナストランポリン",
    "雪青空",
    "雪ＥＸツララ洞窟",
    "雪ＥＸビューゴー",
    "雲EXドットオンキューブ",
    "雲EX福笑い",
    "雲昼空",
    "ＥＸドンスケ",
    "ＥＸ暗闇(ファイバー)"
};

__attribute__((used)) static const char* presetListTranslated[] = {
    "3D Editor White space for confirmation (UNUSED)",
    "Default (USED)",
    "EX Capture Parade (UNUSED)",
    "EX zipper (sub moon area) (USED)",
    "EX zipper (after key acquisition) (UNUSED)",
    "EX zipper (USED)",
    "EX Hat Rotating Labyrinth (USED)",
    "EX Building Rotation (USED)",
    "EX Pole Climbing (UNUSED)",
    "EX Underwater clay pipe (USED)",
    "EX General Purpose Dark Sky (UNUSED)",
    "EX Different Dimension Sky (Grayish) (UNUSED)",
    "EX Different Dimension Sky (Champagne Gold) (UNUSED)",
    "EX Different Dimension Sky (Daltone) (USED)",
    "EX Different Dimension Sky (Pastel) (UNUSED)",
    "EX Different Dimension Sky (Bright) (UNUSED)",
    "EX Different Dimension Sky (Dark Sky) (UNUSED)",
    "EX Different Dimension Sky (Blue Space) (UNUSED)",
    "Bowser Battle Lv3 (after clearing) (UNUSED)",
    "Shop (warm colors) (USED)",
    "Staff roll (USED)",
    "Slot room (USED)",
    "Demo Ending Moon (Flying Jump) (UNUSED)",
    "Demo ending lunar surface (USED)",
    "Demo ending Moon takeoff (UNUSED)",
    "Demo opening (USED)",
    "Encounter with Demo Cap (Kuppa) (UNUSED)",
    "Demo Kuppa's Attack Home Fall (Tiara Up) (UNUSED)",
    "Demo Kuppa's Attack Home Fall (Cloud Day Sky) (USED)",
    "Demo Bowser Capture (UNUSED)",
    "Demo Kuppa Battleship Discovered (Cut Inside Home) (UNUSED)",
    "Demo Kuppa Battleship Discovery (Cloud Day Sky) (USED)",
    "Demo Diver White Space (UNUSED)",
    "Demo Home Move (Return) (USED)",
    "Demo World Warp (USED)",
    "Demo World Move (Inside Home) (UNUSED)",
    "Demo World Move (Evening) (USED)",
    "Demo World Move (Night) (USED)",
    "Demo World Movement (Space) (USED)",
    "Demo World Move (Storm) (USED)",
    "Demo World Move (Day) (USED)",
    "Demo World Move (Cloudy) (USED)",
    "Demo World Move (between the moon and the earth) (USED)",
    "First demo capture (second half inside the tower) (UNUSED)",
    "Demonstration first capture Frog memory (inside the tower) (UNUSED)",
    "Demo first capture frog memory (USED)",
    "Electric wire move to demo waterfall world (UNUSED)",
    "Demonstration Desert Boss Knuckle (UNUSED)",
    "Demonstration Raid Boss Attack (USED)",
    "Peach (64 courtyard) (USED)",
    "Peach EX Yoshi Cloud (USED)",
    "Peach EX Fukuwarai (USED)",
    "Peach World (Peach Castle Hall) (USED)",
    "Peach World (Small Room Boss Entrance) (USED)",
    "Peach World (Outdoor) (USED)",
    "Peach World (for outdoor complete) (UNUSED)",
    "Peach Castle Costume Room (UNUSED)",
    "Peach Castle World EX High Difficulty Dot (USED)",
    "Play guide (UNUSED)",
    "Player Light (Closet) ",
    "Player Light (Shop) ",
    "Player Light (Pose) ",
    "Player Light (Moon Get) ",
    "For programmer confirmation (TREX experiment) (UNUSED)",
    "Programmer confirmation (UNUSED)",
    "Programmer confirmation part 2 (UNUSED)",
    "Programmer confirmation part 3 (UNUSED)",
    "Programmer confirmation part 4 (UNUSED)",
    "Programmer confirmation part 5 (UNUSED)",
    "Programmer confirmation part 6 (UNUSED)",
    "Programmer confirmation part 7 (UNUSED)",
    "Help shooting space (UNUSED)",
    "Base environment (night) (UNUSED)",
    "Base environment 2D cave (UNUSED)",
    "Base environment: Night (UNUSED)",
    "Base environment: indoor warm colors (UNUSED)",
    "Inside the home (USED)",
    "World map (USED)",
    "Crash EX Imomu Poison (USED)",
    "Crash EX Django (USED)",
    "Crash night sky (USED)",
    "For multi-view photography (UNUSED)",
    "Hat EX Extruded Block (USED)",
    "Hat EX Rolling (USED)",
    "Hat no Sato (inside the tower) (USED)",
    "Hat no Sato EX Frog Search (USED)",
    "Hat no Sato EX Poison Wave (USED)",
    "Hat no Sato Full Moon (USED)",
    "Hat full moon sky (behind the tower) (USED)",
    "Plain EX Lift 2D (USED)",
    "Plain EX Hat Appearance Scaffolding (Deformed) (USED)",
    "Plain EX Hat Appearance Scaffolding (UNUSED)",
    "Plain EX Dinosaurs and Pop'n (USED)",
    "Plain Blue Sky (E3PV Dinosaur Demo) (UNUSED)",
    "Plain blue sky (for production test) (UNUSED)",
    "Plain blue sky (USED)",
    "Moon EX Capture Parade (USED)",
    "Moon EX Moon Gravity Athletic (USED)",
    "Moon Capture Parade (Thank You Area) (USED)",
    "Moon Capture Parade (Forest) (USED)",
    "Moon Capture Parade (Lava) (USED)",
    "Moon Capture Parade (Waterfall) (USED)",
    "Moon Capture Parade (True Base) (USED)",
    "Moon Capture Parade (Sand) (USED)",
    "Moon Capture Parade (City) (USED)",
    "Moon Capture Parade (USED)",
    "Moon Bowser Battle (after clearing) (USED)",
    "Moon Bowser Battle (after 1 damage) (USED)",
    "Moon Bowser Battle (after 2 damage) (USED)",
    "Moon Bowser Battle (USED)",
    "Moon Bowser Battle Lv3 (after clearing) (USED)",
    "Moon Bowser Battle Lv3 (after 1 damage) (USED)",
    "Moon Bowser Battle Lv3 (after 2 damage) (USED)",
    "Moon Bowser Battle Lv3 (USED)",
    "Moon Space Sky (GK 4 consecutive battles) (USED)",
    "Moon Space Sky (Backlight) (USED)",
    "Moon Space Sky (UNUSED)",
    "Moon Space Sky True Capture Parade (USED)",
    "Moon Treasure Chest Room (USED)",
    "Moon collapse (intermediate area) (USED)",
    "Moon collapse (final area) (USED)",
    "Moon collapse (USED)",
    "Inside the Moon Church (USED)",
    "Farside EX Galaxy 2 (USED)",
    "Farside EX Shooting City (USED)",
    "Farside EX Bike (USED)",
    "Farside EX Poison Pakkun EX (USED)",
    "Dark side EX ups and downs (USED)",
    "Dark side of the moon GK 4 consecutive battle boss room (USED)",
    "Moon Back True Capture Nebula Space Sky (UNUSED)",
    "Sea of ​​the Moon (USED)",
    "Forest (Jukai area) (USED)",
    "Mori EX Killer Road (USED)",
    "Mori EX Shooting Elevator (USED)",
    "Forest EX Senoby Cloud Bonus (USED)",
    "Mori EX Poison Pakkun (USED)",
    "Forest EX rail generation (USED)",
    "Forest EX Shepherd (USED)",
    "Forest EX Fog Mountain (USED)",
    "Forest Athletic Reward Room (USED)",
    "Forest Costume Room (USED)",
    "Inside Mori Tower (USED)",
    "Forest cloudy sky (in the tunnel) (USED)",
    "Forest cloudy sky (forest area) (USED)",
    "Forest cloudy sky (mechanical area) (USED)",
    "Moriki Kaiho Box Room (USED)",
    "Forest blue sky (inside the tunnel) (USED)",
    "Mori Aozora (Block Boss) (UNUSED)",
    "Forest blue sky (boss) (USED)",
    "Forest blue sky (forest area) (USED)",
    "Forest blue sky (machine area) (USED)",
    "Forest blue sky (UNUSED)",
    "After the forest blue sky flowers bloom (in the tunnel) (USED)",
    "Forest blue sky after flower bloom (forest area) (USED)",
    "After the forest blue sky flowers bloom (mechanical area) (USED)",
    "General-purpose EX cube (dark) (UNUSED)",
    "Sea (costume room) (USED)",
    "Sea (small room) (UNUSED)",
    "Sea (vibration small room) (USED)",
    "Sea (small room underwater) (USED)",
    "Umi EX Kosokoso-kun Room (USED)",
    "Sea EX Senoby Tower (USED)",
    "Sea EX Hosui Valley (valley bottom area) (USED)",
    "Sea EX Hosui Valley (USED)",
    "Sea EX Hat Rotating Spiny (USED)",
    "Sea EX Sea of ​​Clouds (USED)",
    "Sea sunset (no godley because it is underwater) (USED)",
    "Sea sunset (USED)",
    "Sea weather rain sky (boss rematch) (USED)",
    "Sea cave (USED)",
    "Sea blue sky (USED)",
    "Sea Blue Sky EX Reflective Bomb (USED)",
    "Lake EX trampoline hanging (USED)",
    "Lake Frog Poison Swamp (USED)",
    "Lake Gotogoton (USED)",
    "Lake night (underwater) (USED)",
    "Lake night (USED)",
    "Lake day (USED)",
    "Lava EX Gab Elephant Rock (USED)",
    "Lava EX clock (USED)",
    "Lava EX Fork (USED)",
    "Lava EX Pecho's Path (USED)",
    "Lava EX common (UNUSED)",
    "Lava EX excavation (USED)",
    "Lava EX ups and downs (USED)",
    "Lava EX Lava Cruise (USED)",
    "Lava EX Wire Mesh Lift (USED)",
    "Lava Costume Room (USED)",
    "Lava Demo Scenario 1 End (USED)",
    "Lava erupting (UNUSED)",
    "Before lava eruption (vertical light for adjusting shadow orientation) (USED)",
    "Before lava eruption (USED)",
    "During lava eruption (vertical light for adjusting shadow orientation) (USED)",
    "During a lava eruption (USED)",
    "Lava treasure chest room (USED)",
    "Lava cave (USED)",
    "Waterfall EX Sideways Updraft (USED)",
    "Sand EX Hosui Channel (USED)",
    "Sand EX Vibration Small Room (USED)",
    "Desert EX Killer (USED)",
    "Desert EX Sphinx Run (USED)",
    "Desert EX Glasses (USED)",
    "Desert EX Glasses Lift (USED)",
    "Desert Costume Room (USED)",
    "Inside the Desert Pyramid (USED)",
    "Desert Boss Knuckle (USED)",
    "Desert Boss Knuckle OmitDof (UNUSED)",
    "Desert Night Sky (USED)",
    "Desert day (UNUSED)",
    "Desert daylight (for 2016_10 video) (USED)",
    "Desert daylight (USED)",
    "Desert cloudy (UNUSED)",
    "Desert Morning (UNUSED)",
    "Desert Ice Underground (USED)",
    "Desert Golden Room (USED)",
    "Sky EX Tukkun Climb (USED)",
    "Sky EX Tukkun Rotation (USED)",
    "Sky EX Patakaron (USED)",
    "Sky EX Jizo (USED)",
    "Sky EX Cloud Bonus (USED)",
    "Sky Sunset Sky (UNUSED)",
    "Sky Night Sky (after clearing) (USED)",
    "Sky Night Sky (Demonstration of Moon Rock Release after Clearing) (USED)",
    "Sky Night Sky (USED)",
    "Empty folding screen room (USED)",
    "Sky Cloudy Sky (Moon Rock Liberation Demo) (UNUSED)",
    "Sky Cloudy Sky (UNUSED)",
    "Sky blue sky (UNUSED)",
    "Sky Golden Room (USED)",
    "Raid EX Dot Tower (USED)",
    "Raid EX Bull Run (USED)",
    "Raid Storm Sky (Erase Godley after clearing) (USED)",
    "Raid Storm Sky (High Contrast) (UNUSED)",
    "Raid Storm Sky (Moon Rock Demo Godley Eraser) (USED)",
    "Raid Storm Sky (Ice Rematch) (USED)",
    "Raid Storm Sky (Ice Rematch God Layoff) (USED)",
    "Raid Arashi Sky (focusing on production) (USED)",
    "Raid Storm Sky (USED)",
    "City EX 2D Preview Room (USED)",
    "City EX hanging (USED)",
    "City EX wobbly steel frame (USED)",
    "City EX Shooting City (USED)",
    "City EX Bike (USED)",
    "City EX Dinosaurs and Bikes (USED)",
    "City EX Pole Climbing (USED)",
    "City EX Crowd (USED)",
    "City EX Electric Wire (USED)",
    "City EX Musical Note Room (USED)",
    "City Concert Venue (USED)",
    "Inside the City building (daytime) (UNUSED)",
    "City building interior night (USED)",
    "Inside the City building noon (USED)",
    "City radio control room (USED)",
    "City Underground Factory (Core Area) (USED)",
    "City underground factory (rotary scaffolding area) (USED)",
    "City underground factory (passage area) (USED)",
    "City Night Ceremony Live (Moon Get) (USED)",
    "City Night Ceremony Live (USED)",
    "City night sky (starting point) (UNUSED)",
    "City night sky (USED)",
    "Bright City night sky (2D area near the ground) (USED)",
    "Brightening the City night sky (USED)",
    "City daytime rainy sky (USED)",
    "City Blue Sky (Diver Demo A) (UNUSED)",
    "City blue sky (for Diver still images) (UNUSED)",
    "City blue sky (starting point: no automatic exposure) (USED)",
    "City blue sky (player light verification) (UNUSED)",
    "City Blue Sky (Main Visual) (UNUSED)",
    "City blue sky (photo test) (UNUSED)",
    "City blue sky (USED)",
    "Snow EX Ice Walker (USED)",
    "Snow EX killer rail generation (USED)",
    "Snow EX Dot Round Tower (USED)",
    "Snow EX View Go Puzzle (USED)",
    "Snow EX Ice Dash (USED)",
    "Snow EX Ice Water Block (USED)",
    "For snow circuit photography (UNUSED)",
    "Snowy night sky (circuit) (USED)",
    "Snow room (race entrance) (USED)",
    "Snow room (USED)",
    "Snow cloudy sky (circuit) (USED)",
    "Snow cloudy sky (dense fog) (USED)",
    "Snow cloudy sky (GK battle) (USED)",
    "Snow Cloud Bonus Trampoline (USED)",
    "Snow blue sky (USED)",
    "Snow EX Tsurara Cave (USED)",
    "Snow EX View Go (USED)",
    "Cloud EX Dot on Cube (USED)",
    "Cloud EX Fukuwarai (USED)",
    "Cloud day sky (USED)",
    "EX Donsuke (USED)",
    "EX Darkness (Fiber) (UNUSED)"
};

__attribute__((used)) static const char* cubemapList[] = {
    "AnimalChaseExStage",
    "BikeSteelExStage",
    "BikeSteelNoCapExStage",
    "BossRaidWorldHomeStage",
    "BullRunExStage",
    "ByugoPuzzleExStage",
    "CapAppearExStage",
    "CapAppearLavaLiftExStage",
    "CapRotatePackunExStage",
    "CapWorldHomeStage",
    "CapWorldTowerStage",
    "CityPeopleRoadStage",
    "CityWorldFactoryStage",
    "CityWorldHomeStage",
    "CityWorldMainTowerStage",
    "CityWorldSandSlotStage",
    "CityWorldShop01Stage",
    "ClashWorldHomeStage",
    "ClashWorldShopStage",
    "CloudExStage",
    "CloudWorldHomeStage",
    "Cube2DExStage",
    "DemoBossRaidAttackStage",
    "DemoChangeWorldBossRaidAttackStage",
    "DemoChangeWorldFindKoopaShipStage",
    "DemoChangeWorldStage",
    "DemoCrashHomeFallStage",
    "DemoCrashHomeStage",
    "DemoEndingStage",
    "DemoLavaWorldScenario1EndStage",
    "DemoOpeningStage",
    "DemoWorldMoveBackwardArriveStage",
    "DemoWorldMoveBackwardStage",
    "DemoWorldMoveForwardArriveStage",
    "DemoWorldMoveForwardFirstStage",
    "DemoWorldMoveForwardStage",
    "DemoWorldMoveMoonBackwardStage",
    "DemoWorldMoveMoonForwardFirstStage",
    "DemoWorldMoveMoonForwardStage",
    "DemoWorldWarpHoleStage",
    "DonsukeExStage",
    "DotHardExStage",
    "DotTowerExStage",
    "ElectricWireExStage",
    "FastenerExStage",
    "FogMountainExStage",
    "ForestWorldBonusStage",
    "ForestWorldBossStage",
    "ForestWorldCloudBonusExStage",
    "ForestWorldHomeStage",
    "ForestWorldTowerStage",
    "ForestWorldWaterExStage",
    "ForestWorldWoodsCostumeStage",
    "ForestWorldWoodsStage",
    "ForestWorldWoodsTreasureStage",
    "ForkExStage",
    "FrogPoisonExStage",
    "FrogSearchExStage",
    "FukuwaraiKuriboStage",
    "FukuwaraiMarioStage",
    "GabuzouClockExStage",
    "Galaxy2DExStage",
    "GotogotonExStage",
    "HomeShipInsideStage",
    "IceWalkerExStage",
    "IceWaterBlockExStage",
    "IceWaterDashExStage",
    "ImomuPoisonExStage",
    "JangoExStage",
    "JizoSwitchExStage",
    "KaronWingTowerStage",
    "KillerRailCollisionExStage",
    "KillerRoadExStage",
    "KillerRoadNoCapExStage",
    "LakeWorldHomeStage",
    "LakeWorldShopStage",
    "LavaBonus1Zone",
    "LavaWorldBubbleLaneExStage",
    "LavaWorldClockExStage",
    "LavaWorldCostumeStage",
    "LavaWorldExcavationExStage",
    "LavaWorldFenceLiftExStage",
    "LavaWorldHomeStage",
    "LavaWorldShopStage",
    "LavaWorldTreasureStage",
    "LavaWorldUpDownExStage",
    "LavaWorldUpDownYoshiExStage",
    "Lift2DExStage",
    "LightingPlayerClosetStage",
    "LightingPlayerMoonGetStage",
    "LightingPlayerPause000Stage",
    "LightingPlayerShopStage",
    "MeganeLiftExStage",
    "MoonAthleticExStage",
    "MoonWorldBasementStage",
    "MoonWorldCaptureParadeStage",
    "MoonWorldHomeStage",
    "MoonWorldKoopa1Stage",
    "MoonWorldKoopa2Stage",
    "MoonWorldShopRoom",
    "MoonWorldSphinxRoom",
    "MoonWorldWeddingRoom2Stage",
    "MoonWorldWeddingRoomStage",
    "Note2D3DRoomExStage",
    "PackunPoisonExStage",
    "PackunPoisonNoCapExStage",
    "PeachWorldCastleStage",
    "PeachWorldCostumeStage",
    "PeachWorldHomeStage",
    "PeachWorldPictureBossForestStage",
    "PeachWorldPictureBossKnuckleStage",
    "PeachWorldPictureBossMagmaStage",
    "PeachWorldPictureBossRaidStage",
    "PeachWorldPictureGiantWanderBossStage",
    "PeachWorldPictureMofumofuStage",
    "PeachWorldShopStage",
    "PoisonWaveExStage",
    "PoleGrabCeilExStage",
    "PoleKillerExStage",
    "PushBlockExStage",
    "RadioControlExStage",
    "RailCollisionExStage",
    "ReflectBombExStage",
    "RevengeBossKnuckleStage",
    "RevengeBossMagmaStage",
    "RevengeBossRaidStage",
    "RevengeForestBossStage",
    "RevengeGiantWanderBossStage",
    "RevengeMofumofuStage",
    "RocketFlowerExStage",
    "RollingExStage",
    "SandWorldCostumeStage",
    "SandWorldHomeStage",
    "SandWorldKillerExStage",
    "SandWorldMeganeExStage",
    "SandWorldPressExStage",
    "SandWorldPyramid000Stage",
    "SandWorldPyramid001Stage",
    "SandWorldRotateExStage",
    "SandWorldSecretStage",
    "SandWorldShopStage",
    "SandWorldSlotStage",
    "SandWorldSphinxExStage",
    "SandWorldUnderground000Stage",
    "SandWorldUnderground001Stage",
    "SandWorldVibrationStage",
    "SeaWorldCostumeStage",
    "SeaWorldHomeStage",
    "SeaWorldSecretStage",
    "SeaWorldSneakingManStage",
    "SeaWorldUtsuboCaveStage",
    "SeaWorldVibrationStage",
    "SenobiTowerExStage",
    "SenobiTowerYoshiExStage",
    "ShootingCityExStage",
    "ShootingCityYoshiExStage",
    "ShootingElevatorExStage",
    "SkyWorldCloudBonusExStage",
    "SkyWorldCostumeStage",
    "SkyWorldHomeStage",
    "SkyWorldShopStage",
    "SkyWorldTreasureStage",
    "SnowWorldBalconyZone",
    "SnowWorldByugoZone",
    "SnowWorldCloudBonusExStage",
    "SnowWorldCostumeStage",
    "SnowWorldGabuzouZone",
    "SnowWorldHomeStage",
    "SnowWorldIcicleZone",
    "SnowWorldLobby000Stage",
    "SnowWorldLobby001Stage",
    "SnowWorldLobbyExStage",
    "SnowWorldRace000Stage",
    "SnowWorldRace001Stage",
    "SnowWorldRaceExStage",
    "SnowWorldRaceGroundZone",
    "SnowWorldRaceHardExStage",
    "SnowWorldRaceTutorialStage",
    "SnowWorldShopStage",
    "SnowWorldTownStage",
    "SnowWorldTownZone",
    "Special1WorldHomeStage",
    "Special1WorldTowerBombTailStage",
    "Special1WorldTowerCapThrowerStage",
    "Special1WorldTowerFireBlowerStage",
    "Special1WorldTowerStackerStage",
    "Special2WorldCloudStage",
    "Special2WorldHomeStage",
    "Special2WorldKoopaStage",
    "Special2WorldLavaStage",
    "SwingSteelExStage",
    "Theater2DExStage",
    "TogezoRotateExStage",
    "TrampolineWallCatchExStage",
    "TrexBikeExStage",
    "TrexPoppunExStage",
    "TsukkunClimbExStage",
    "TsukkunRotateExStage",
    "WanwanClashExStage",
    "WaterfallWorldHomeStage",
    "WaterTubeExStage",
    "WaterValleyExStage",
    "WindBlowExStage",
    "WorldMapStage",
    "YoshiCloudExStage"
};

__attribute__((used)) static const char* skyList[] = {
    "SkyCityCloudy",
    "SkyCityDayLight",
    "SkyCityNightRain",
    "SkyCityNightStar",
    "SkyCloudMorning",
    "SkyCrashRomantic",
    "SkyDark",
    "SkyDemoMoonGet",
    "SkyDemoWorldMove",
    "SkyDemoWorldMoveCloudy",
    "SkyDemoWorldMoveMoonSpace",
    "SkyDemoWorldMoveNight",
    "SkyDemoWorldMoveStorm",
    "SkyDemoWorldMoveSunset",
    "SkyDesertDayCold",
    "SkyDesertDayHot",
    "SkyDesertIceCave",
    "SkyDesertNight",
    "SkyExDifferentWorldBlueBright",
    "SkyExDifferentWorldDark",
    "SkyExDullToneColor",
    "SkyExGreyColor",
    "SkyExPastelColor",
    "SkyForestCloudy",
    "SkyForestDayDark",
    "SkyForestDayLight",
    "SkyHatVillageNight",
    "SkyLakeDay",
    "SkyLakeNight",
    "SkyLavaWonderfulCream",
    "SkyLavaWonderfulPink",
    "SkyMoonSpace",
    "SkyMoonSpaceCapture",
    "SkyPeachCastleDay",
    "SkyPeachCastleMorning",
    "SkyPeachCastleOpening",
    "SkyRaidCloudy",
    "SkySeaDay",
    "SkySeaSunset",
    "SkySkyNight",
    "SkySnowDayLight",
    "SkySnowDayRace",
    "SkySnowDaySnowStorm",
    "SkySnowNightRace",
    "SkyWaterFallsBlue"
};