#pragma once

#include "sead/math/seadVector.h"

#include "HitSensor.h"
#include "SensorMsg.h"

namespace al
{

    struct ComboCounter;
    struct EventFlowExecutor;
    struct ParabolicPath;

    bool sendMsgPlayerAttackTrample(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerTrampleReflect(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerReflectOrTrample(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerHipDrop(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerObjHipDrop(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerObjHipDropReflect(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerObjHipDropHighJump(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerHipDropKnockDown(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerStatueDrop(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerObjStatueDrop(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerObjStatueDropReflect(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerObjStatueDropReflectNoCondition(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerStatueTouch(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerUpperPunch(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerObjUpperPunch(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerRollingAttack(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerRollingReflect(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerObjRollingAttack(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerObjRollingAttackFailure(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerInvincibleAttack(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerFireBallAttack(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerRouteDokanFireBallAttack(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerTailAttack(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerTouch(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerKick(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerCatch(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerSlidingAttack(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerBoomerangAttack(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerBoomerangAttackCollide(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerBoomerangReflect(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerBoomerangBreak(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerBodyAttack(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerBodyLanding(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerBodyAttackReflect(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerClimbAttack(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerSpinAttack(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerGiantAttack(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerCooperationHipDrop(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerClimbSlidingAttack(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerClimbRollingAttack(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerGiantHipDrop(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPlayerDisregard(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerItemGet(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerPutOnEquipment(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerReleaseEquipment(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerReleaseEquipmentGoal(al::HitSensor *, al::HitSensor *, uint);
    bool sendMsgPlayerFloorTouch(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerDamageTouch(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerCarryFront(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerCarryFrontWallKeep(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerCarryUp(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerCarryKeepDemo(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerCarryWarp(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerLeave(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerRelease(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerReleaseBySwing(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerReleaseDamage(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerReleaseDead(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerReleaseDemo(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerToss(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerInvincibleTouch(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgEnemyAttack(al::HitSensor *, al::HitSensor *);
    bool sendMsgEnemyAttackBoomerang(al::HitSensor *, al::HitSensor *);
    bool sendMsgEnemyAttackFire(al::HitSensor *, al::HitSensor *, char const *);
    bool sendMsgEnemyAttackNeedle(al::HitSensor *, al::HitSensor *);
    bool sendMsgEnemyFloorTouch(al::HitSensor *, al::HitSensor *);
    bool sendMsgEnemyItemGet(al::HitSensor *, al::HitSensor *);
    bool sendMsgEnemyRouteDokanAttack(al::HitSensor *, al::HitSensor *);
    bool sendMsgEnemyRouteDokanFire(al::HitSensor *, al::HitSensor *);
    bool sendMsgEnemyTouch(al::HitSensor *, al::HitSensor *);
    bool sendMsgEnemyUpperPunch(al::HitSensor *, al::HitSensor *);
    bool sendMsgEnemyTrample(al::HitSensor *, al::HitSensor *);
    bool sendMsgMapObjTrample(al::HitSensor *, al::HitSensor *);
    bool sendMsgPressureDeath(al::HitSensor *, al::HitSensor *);
    bool sendMsgNpcTouch(al::HitSensor *, al::HitSensor *);
    bool sendMsgExplosion(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgExplosionCollide(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgPush(al::HitSensor *, al::HitSensor *);
    bool sendMsgPushStrong(al::HitSensor *, al::HitSensor *);
    bool sendMsgPushVeryStrong(al::HitSensor *, al::HitSensor *);
    bool sendMsgHit(al::HitSensor *, al::HitSensor *);
    bool sendMsgHitStrong(al::HitSensor *, al::HitSensor *);
    bool sendMsgHitVeryStrong(al::HitSensor *, al::HitSensor *);
    bool sendMsgKnockDown(al::HitSensor *, al::HitSensor *);
    bool sendMsgMapPush(al::HitSensor *, al::HitSensor *);
    bool sendMsgVanish(al::HitSensor *, al::HitSensor *);
    bool sendMsgChangeAlpha(al::LiveActor *, float);
    bool sendMsgShowModel(al::HitSensor *, al::HitSensor *);
    bool sendMsgHideModel(al::HitSensor *, al::HitSensor *);
    bool sendMsgRestart(al::HitSensor *, al::HitSensor *);
    bool sendMsgNeedleBallAttack(al::HitSensor *, al::HitSensor *);
    bool sendMsgPunpunFloorTouch(al::HitSensor *, al::HitSensor *);
    bool sendMsgInvalidateFootPrint(al::HitSensor *, al::HitSensor *);
    bool sendMsgKickKouraAttack(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgKickKouraAttackCollide(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgKickKouraGetItem(al::HitSensor *, al::HitSensor *);
    bool sendMsgKickKouraReflect(al::HitSensor *, al::HitSensor *);
    bool sendMsgKickKouraCollideNoReflect(al::HitSensor *, al::HitSensor *);
    bool sendMsgKickKouraBreak(al::HitSensor *, al::HitSensor *);
    bool sendMsgKickKouraBlow(al::HitSensor *, al::HitSensor *);
    bool sendMsgKickStoneAttack(al::HitSensor *, al::HitSensor *);
    bool sendMsgKickStoneAttackCollide(al::HitSensor *, al::HitSensor *);
    bool sendMsgKickStoneAttackHold(al::HitSensor *, al::HitSensor *);
    bool sendMsgKickStoneAttackReflect(al::HitSensor *, al::HitSensor *);
    bool sendMsgKickStoneTrample(al::HitSensor *, al::HitSensor *);
    bool sendMsgKillerAttack(al::HitSensor *, al::HitSensor *);
    bool sendMsgLiftGeyser(al::HitSensor *, al::HitSensor *);
    bool sendMsgWarpStart(al::HitSensor *, al::HitSensor *);
    bool sendMsgWarpEnd(al::HitSensor *, al::HitSensor *);
    bool sendMsgHoldCancel(al::HitSensor *, al::HitSensor *);
    bool sendMsgHoleIn(al::HitSensor *, al::HitSensor *);
    bool sendMsgJumpInhibit(al::HitSensor *, al::HitSensor *);
    bool sendMsgGoalKill(al::HitSensor *, al::HitSensor *);
    bool sendMsgGoal(al::HitSensor *, al::HitSensor *);
    bool sendMsgBindStart(al::HitSensor *, al::HitSensor *);
    bool sendMsgBindInit(al::HitSensor *, al::HitSensor *, uint);
    bool sendMsgBindEnd(al::HitSensor *, al::HitSensor *);
    bool sendMsgBindCancel(al::HitSensor *, al::HitSensor *);
    bool sendMsgBindCancelByDemo(al::HitSensor *, al::HitSensor *);
    bool sendMsgBindDamage(al::HitSensor *, al::HitSensor *);
    bool sendMsgBindSteal(al::HitSensor *, al::HitSensor *);
    bool sendMsgBindGiant(al::HitSensor *, al::HitSensor *);
    bool sendMsgBallAttack(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgBallRouteDokanAttack(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgBallAttackHold(al::HitSensor *, al::HitSensor *);
    bool sendMsgBallAttackDRCHold(al::HitSensor *, al::HitSensor *);
    bool sendMsgBallAttackCollide(al::HitSensor *, al::HitSensor *);
    bool sendMsgBallTrample(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgBallTrampleCollide(al::HitSensor *, al::HitSensor *);
    bool sendMsgBallItemGet(al::HitSensor *, al::HitSensor *);
    bool sendMsgFireBalCollide(al::HitSensor *, al::HitSensor *);
    bool sendMsgFireBallFloorTouch(al::HitSensor *, al::HitSensor *);
    bool sendMsgDokanBazookaAttack(al::HitSensor *, al::HitSensor *);
    bool sendMsgRideAllPlayerItemGet(al::HitSensor *, al::HitSensor *);
    bool sendMsgHideModel(al::LiveActor *);
    bool sendMsgShowModel(al::LiveActor *);
    bool sendMsgRestart(al::LiveActor *);
    bool sendMsgCollisionImpulse(al::HitSensor *, al::HitSensor *, sead::Vector3f *, sead::Vector3f const &, float, sead::Vector3f const &, float);
    bool sendMsgSwitchOn(al::LiveActor *);
    bool sendMsgSwitchOnInit(al::LiveActor *);
    bool sendMsgSwitchOffInit(al::LiveActor *);
    bool sendMsgSwitchKillOn(al::LiveActor *);
    bool sendMsgSwitchKillOnInit(al::LiveActor *);
    bool sendMsgSwitchKillOffInit(al::LiveActor *);
    bool sendMsgPlayerFloorTouchToColliderGround(al::LiveActor *, al::HitSensor *);
    bool sendMsgPlayerUpperPunchToColliderCeiling(al::LiveActor *, al::HitSensor *);
    bool sendMsgEnemyFloorTouchToColliderGround(al::LiveActor *, al::HitSensor *);
    bool sendMsgEnemyUpperPunchToColliderCeiling(al::LiveActor *, al::HitSensor *);
    bool sendMsgAskSafetyPoint(al::HitSensor *, al::HitSensor *, sead::Vector3f **);
    bool sendMsgAskSafetyPointToColliderGround(al::LiveActor *, al::HitSensor *, sead::Vector3f **);
    bool sendMsgTouchAssist(al::HitSensor *, al::HitSensor *);
    bool sendMsgTouchAssistTrig(al::HitSensor *, al::HitSensor *);
    bool sendMsgTouchStroke(al::HitSensor *, al::HitSensor *);
    bool sendMsgScreenPointInvalidCollisionParts(al::HitSensor *, al::HitSensor *);
    bool sendMsgBlockUpperPunch(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgBlockLowerPunch(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgBlockItemGet(al::HitSensor *, al::HitSensor *);
    bool sendMsgKillerItemGet(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerKouraAttack(al::HitSensor *, al::HitSensor *, al::ComboCounter *);
    bool sendMsgLightFlash(al::HitSensor *, al::HitSensor *);
    bool sendMsgForceAbyss(al::HitSensor *, al::HitSensor *);
    bool sendMsgIsNerveSupportFreeze(al::HitSensor *, al::HitSensor *);
    bool sendMsgOnSyncSupportFreeze(al::HitSensor *, al::HitSensor *);
    bool sendMsgOffSyncSupportFreeze(al::HitSensor *, al::HitSensor *);
    bool sendMsgSwordAttackHighLeft(al::HitSensor *, al::HitSensor *);
    bool sendMsgSwordAttackLowLeft(al::HitSensor *, al::HitSensor *);
    bool sendMsgSwordAttackHighRight(al::HitSensor *, al::HitSensor *);
    bool sendMsgSwordAttackLowRight(al::HitSensor *, al::HitSensor *);
    bool sendMsgSwordAttackJumpUnder(al::HitSensor *, al::HitSensor *);
    bool sendMsgSwordBeamAttack(al::HitSensor *, al::HitSensor *);
    bool sendMsgSwordBeamReflectAttack(al::HitSensor *, al::HitSensor *);
    bool sendMsgShieldGuard(al::HitSensor *, al::HitSensor *);
    bool sendMsgEnemyAttackKnockDown(al::HitSensor *, al::HitSensor *);
    bool sendMsgAskMultiPlayerEnemy(al::HitSensor *, al::HitSensor *);
    bool sendMsgItemGettable(al::HitSensor *, al::HitSensor *);
    bool sendMsgKikkiThrow(al::HitSensor *, al::HitSensor *);
    bool sendMsgIsKikkiThrowTarget(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerCloudGet(al::HitSensor *, al::HitSensor *);
    bool sendMsgAutoJump(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerTouchShadow(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerPullOutShadow(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerAttackShadow(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerAttackShadowStrong(al::HitSensor *, al::HitSensor *);
    bool sendMsgPlayerAttackChangePos(al::HitSensor *, al::HitSensor *, sead::Vector3f *);
    bool sendMsgAtmosOnlineLight(al::HitSensor *, al::HitSensor *);
    bool sendMsgLightBurn(al::HitSensor *, al::HitSensor *);
    bool sendMsgMoonLightBurn(al::HitSensor *, al::HitSensor *);
    bool sendMsgString(al::HitSensor *, al::HitSensor *, char const *);
    bool sendMsgStringV4fPtr(al::HitSensor *, al::HitSensor *, char const *, sead::Vector4f *);
    bool sendMsgStringV4fSensorPtr(al::HitSensor *, al::HitSensor *, char const *, sead::Vector4f *);
    bool sendMsgStringVoidPtr(al::HitSensor *, al::HitSensor *, char const *, void *);
    bool sendMsgEnemyAttackForCrossoverSensor(al::HitSensor *, al::HitSensor *);
    bool sendMsgEnemyAttackForCrossoverCylinderSensor(al::HitSensor *, al::HitSensor *, sead::Vector3f const &, sead::Vector3f const &, float);
    bool sendMsgPushAndKillVelocityToTarget(al::LiveActor *, al::HitSensor *, al::HitSensor *);
    bool sendMsgPushAndKillVelocityToTargetH(al::LiveActor *, al::HitSensor *, al::HitSensor *);
    bool sendMsgCollidePush(al::HitSensor *, al::HitSensor *, sead::Vector3f const &);
    bool sendMsgScreenPointTarget(al::SensorMsg const &, al::ScreenPointer *, al::ScreenPointTarget *);

} // namespace al

struct SaveObjInfo;
struct HackEndParam;
struct IUsePlayerCollision;
struct IUsePlayerHack;

struct DigPoint;
struct TouchTargetInfo;
struct WhipTargetInfo;
struct CapTargetInfo;
struct GotogotonMark;
struct FishingFish;

namespace rs
{
    bool sendMsgHackerNoReaction(IUsePlayerHack const*,al::HitSensor *,al::HitSensor *);
    bool sendMsgHackerNoReactionWithoutShine(IUsePlayerHack const*,al::HitSensor *,al::HitSensor *);
    bool sendMsgBreakFloorToPlayer(al::LiveActor const*);
    bool sendMsgAckCheckpoint(al::HitSensor *,al::HitSensor *);
    bool sendMsgAckGetShine(al::HitSensor *,al::HitSensor *);
    bool sendMsgAckLifeUp(al::HitSensor *,al::HitSensor *);
    bool sendMsgAckLifeMaxUp(al::HitSensor *,al::HitSensor *);
    bool sendMsgAskRailCollision(al::HitSensor *,al::HitSensor *);
    bool sendMsgBreakPartsBreak(al::HitSensor *,al::HitSensor *);
    bool sendMsgBirdFlyAway(al::HitSensor *,al::HitSensor *);
    bool sendMsgCameraAngleElevationResetFast(al::HitSensor *,al::HitSensor *);
    bool sendMsgChorobonAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgConductLightning(al::HitSensor *,al::HitSensor *);
    bool sendMsgDamageBallAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgDamageBallBodyAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgDonsukeAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgDonsukeGroundAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgDonsukePush(al::HitSensor *,al::HitSensor *);
    bool sendMsgDragonAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgEatExplosion(al::HitSensor *,al::HitSensor *);
    bool sendMsgElectricWireNoLimitDistance(al::HitSensor *,al::HitSensor *);
    bool sendMsgEnemyAttack2D(al::HitSensor *,al::HitSensor *);
    bool sendMsgEnemyAttack3D(al::HitSensor *,al::HitSensor *);
    bool sendMsgEnemyAttackDash(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackAttackFire(al::HitSensor *,al::HitSensor *);
    bool sendMsgEnemyAttackFireCollision(al::HitSensor *,al::HitSensor *);
    bool sendMsgEnemyAttackPoison(al::HitSensor *,al::HitSensor *);
    bool sendMsgEnemyAttackTRex(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackAttackPoison(al::HitSensor *,al::HitSensor *);
    bool sendMsgConfirmPaintObj(al::HitSensor *,al::HitSensor *);
    bool sendMsgConfirmPaintObjForSeed(al::HitSensor *,al::HitSensor *);
    bool sendMsgPaintAttackPoison(al::HitSensor *,al::HitSensor *);
    bool sendMsgEnemyKick(al::HitSensor *,al::HitSensor *);
    bool sendMsgRabbitKick(al::HitSensor *,al::HitSensor *);
    bool sendMsgFishingAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgFishingCancel(al::HitSensor *,al::HitSensor *);
    bool sendMsgFishingFishApproach(al::HitSensor *,al::HitSensor *);
    bool sendMsgFishingFishFloatTouch(al::HitSensor *,al::HitSensor *);
    bool sendMsgFishingItemGet(al::HitSensor *,al::HitSensor *);
    bool sendMsgFishingLineTouch(al::HitSensor *,al::HitSensor *);
    bool sendMsgFishingStart(al::HitSensor *,al::HitSensor *);
    bool sendMsgFishingUpImmediatelyPrepare(al::HitSensor *,al::HitSensor *);
    bool sendMsgFireBrosFireBallCollide(al::HitSensor *,al::HitSensor *);
    bool sendMsgFireSwitchFire(al::HitSensor *,al::HitSensor *);
    bool sendMsgFrogHackTrample(al::HitSensor *,al::HitSensor *);
    bool sendMsgGhostRecordStart(al::HitSensor *,al::HitSensor *);
    bool sendMsgGhostRecordEnd(al::HitSensor *,al::HitSensor *);
    bool sendMsgGhostPlay(al::HitSensor *,al::HitSensor *);
    bool sendMsgGhostStop(al::HitSensor *,al::HitSensor *);
    bool sendMsgGiantWanderBossAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgGiantWanderBossBulletAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgGiantWanderBossBulletPush(al::HitSensor *,al::HitSensor *);
    bool sendMsgGhostReverse(al::HitSensor *,al::HitSensor *);
    bool sendMsgGhostCancel(al::HitSensor *,al::HitSensor *);
    bool sendMsgGrowFlowerSeedDisablePush(al::HitSensor *,al::HitSensor *);
    bool sendMsgGrowFlowerSeedNear(al::HitSensor *,al::HitSensor *);
    bool sendMsgGrowPlantPush(al::HitSensor *,al::HitSensor *);
    bool sendMsgGrowerAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgGrowerWallAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgGunetterAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgGunetterBodyTouch(al::HitSensor *,al::HitSensor *);
    bool sendMsgHammerAttackDown(al::HitSensor *,al::HitSensor *);
    bool sendMsgHammerAttackSide(al::HitSensor *,al::HitSensor *);
    bool sendMsgHammerAttackSideCollide(al::HitSensor *,al::HitSensor *);
    bool sendMsgItemAmiiboKoopa(al::HitSensor *,al::HitSensor *);
    bool sendMsgIsExistPukupuku(al::HitSensor *,al::HitSensor *);
    bool sendMsgJangoAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgJangoRemoveCap(al::HitSensor *,al::HitSensor *);
    bool sendMsgKakkuKick(al::HitSensor *,al::HitSensor *);
    bool sendMsgKillByBossBattleDemo(al::HitSensor *,al::HitSensor *);
    bool sendMsgKillByHackFirstDemo(al::HitSensor *,al::HitSensor *);
    bool sendMsgKillByHomeDemo(al::HitSensor *,al::HitSensor *);
    bool sendMsgEndHomeDemo(al::HitSensor *,al::HitSensor *);
    bool sendMsgKillByMoonRockDemo(al::HitSensor *,al::HitSensor *);
    bool sendMsgKillByShineGet(al::HitSensor *,al::HitSensor *);
    bool sendMsgKillBySwitchTimer(al::LiveActor *);
    bool sendMsgKoopaBindStart(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaCapPlayerFocusTarget(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaCapPunchFinishL(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaCapPunchFinishR(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaCapPunchInvincibleL(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaCapPunchInvincibleR(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaCapPunchKnockBackL(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaCapPunchKnockBackR(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaCapPunchL(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaCapPunchR(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaCapSpinAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaCatchKoopaCap(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaDashPunchAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaFire2D(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaFireBallAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaHackDamage(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaHackPunch(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaHackPunchCollide(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaHackTrample(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaInvalidHackPunchFaceToCollision(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaRingBeamInvalidTouch(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaTailAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgKoopaTouchFloor(al::HitSensor *,al::HitSensor *);
    bool sendMsgKouraAttack2D(al::HitSensor *,al::HitSensor *);
    bool sendMsgKouraItemGet2D(al::HitSensor *,al::HitSensor *);
    bool sendMsgLaunchBlow(al::HitSensor *,al::HitSensor *);
    bool sendMsgMeganeAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgMeganeHackTrample(al::HitSensor *,al::HitSensor *);
    bool sendMsgMofumofuBulletUnexplosion(al::HitSensor *,al::HitSensor *);
    bool sendMsgMoonBasementAttackMeteor(al::HitSensor *,al::HitSensor *);
    bool sendMsgMoonBasementBreakShockwaveMeteor(al::HitSensor *,al::HitSensor *);
    bool sendMsgMoonBasementRockSyncClippingRegist(al::HitSensor *,al::HitSensor *);
    bool sendMsgMoonBasementRockSyncClippingInvalidate(al::HitSensor *,al::HitSensor *);
    bool sendMsgMoonBasementRockSyncClippingValidate(al::HitSensor *,al::HitSensor *);
    bool sendMsgAttachCactusNeedle(al::HitSensor *,al::HitSensor *);
    bool sendMsgCactusNeedleAttack(al::HitSensor *,al::HitSensor *,al::ComboCounter *);
    bool sendMsgCactusNeedleAttackStrong(al::HitSensor *,al::HitSensor *,al::ComboCounter *);
    bool sendMsgPlayerBallToss(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerCarryCameraSubjectiveStart(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerCarryCameraSubjectiveEnd(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerCarryShineGetStart(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerCarryShineGetEnd(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerCapCatch(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerCapHipDrop(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerCapPush(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerCapRecovery(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerCapTouchJump(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerCapTrample(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerCoinDashGet(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerEyePriorityTarget(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerDisregardHomingAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerDisregardTargetMarker(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerEquipKoopaCap(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerFireBallAttack2D(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerFireBallAttack3D(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerHipDropDemoTrigger(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerHipDropHipDropSwitch(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerItemGet2D(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerJumpTakeOffFloor(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerObjectWallHit(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerObjLeapFrog(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerPenguinAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerPenguinAttackReflect(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerPoleClimbKeep(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerPoleClimbReaction(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerRabbitGet(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerRollingObjHit(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerRollingWallHitDown(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerRollingWallHitMove(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerStartGrabCeil(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerStartWallJump(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerEndGrabCeil(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerSwordAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerTouchFloorJumpCode(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerTrample2D(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerUpperPunch2D(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerObjUpperPunch2D(al::HitSensor *,al::HitSensor *);
    bool sendMsgPukupukuDash(al::HitSensor *,al::HitSensor *);
    bool sendMsgPukupukuKiss(al::HitSensor *,al::HitSensor *);
    bool sendMsgPukupukuRollingAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgPush2D(al::HitSensor *,al::HitSensor *);
    bool sendMsgPushToFish(al::HitSensor *,al::HitSensor *);
    bool sendMsgPushToMotorcycle(al::HitSensor *,al::HitSensor *);
    bool sendMsgPushToPlayer(al::HitSensor *,al::HitSensor *);
    bool sendMsgRadishAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgRadishReflect(al::HitSensor *,al::HitSensor *);
    bool sendMsgRequestChangeKinokoSuper(al::HitSensor *,al::HitSensor *);
    bool sendMsgRequestChangeFireFlower(al::HitSensor *,al::HitSensor *);
    bool sendMsgRequestPlayerSandMoon(al::HitSensor *,al::HitSensor *);
    bool sendMsgRequestPlayerSnow(al::HitSensor *,al::HitSensor *);
    bool sendMsgRequestPlayerWet(al::HitSensor *,al::HitSensor *);
    bool sendMsgStartHack(al::HitSensor *,al::HitSensor *);
    bool sendMsgSunshineAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgCancelHack(al::HitSensor *,al::HitSensor *);
    bool sendMsgCancelHackArea(al::HitSensor *,al::HitSensor *);
    bool sendMsgCancelHackByDokan(al::HitSensor *,al::HitSensor *);
    bool sendMsgPackunEatStart(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackAttackKick(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackAttackMapObj(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackDeathAreaSelfCheck(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackDemoEnd(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackDemoStart(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackInvalidEscape(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackInvalidEscapeNoReaction(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackMarioCheckpointFlagWarp(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackMarioDead(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackMarioDemo(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackMarioInWater(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackMoveRockForestPush(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackSelfCeilingCheckMiss(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackSyncDamageVisibility(al::HitSensor *,al::HitSensor *);
    bool sendMsgWeaponItemGet(al::HitSensor *,al::HitSensor *);
    bool sendMsgCapAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgCapAttackCollide(al::HitSensor *,al::HitSensor *);
    bool sendMsgCapAttackStayRolling(al::HitSensor *,al::HitSensor *);
    bool sendMsgCapAttackStayRollingCollide(al::HitSensor *,al::HitSensor *);
    bool sendMsgCapAttackRailMove(al::HitSensor *,al::HitSensor *);
    bool sendMsgCapGiantAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgCapReflect(al::HitSensor *,al::HitSensor *);
    bool sendMsgCapReflectCollide(al::HitSensor *,al::HitSensor *);
    bool sendMsgCapStartLockOn(al::HitSensor *,al::HitSensor *);
    bool sendMsgCapKeepLockOn(al::HitSensor *,al::HitSensor *);
    bool sendMsgCapCancelLockOn(al::HitSensor *,al::HitSensor *);
    bool sendMsgCapHipDrop(al::HitSensor *,al::HitSensor *);
    bool sendMsgCapObjHipDrop(al::HitSensor *,al::HitSensor *);
    bool sendMsgCapObjHipDropReflect(al::HitSensor *,al::HitSensor *);
    bool sendMsgCapIgnoreCancelLockOn(al::HitSensor *,al::HitSensor *);
    bool sendMsgCapIgnoreCancelMissReaction(al::HitSensor *,al::HitSensor *);
    bool sendMsgCapIgnoreCollisionCheck(al::HitSensor *,al::HitSensor *);
    bool sendMsgCapItemGet(al::HitSensor *,al::HitSensor *);
    bool sendMsgCapTrampolineAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgCatchBombThrough(al::HitSensor *,al::HitSensor *);
    bool sendMsgCheckCarObstacle(al::HitSensor *,al::HitSensor *);
    bool sendMsgCheckIsCardboardBox(al::HitSensor *,al::HitSensor *);
    bool sendMsgBullHackAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgBullEnemyAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgEnemyAttackStrong(al::HitSensor *,al::HitSensor *);
    bool sendMsgEnemyObjBreak(al::HitSensor *,al::HitSensor *);
    bool sendMsgWhipAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgNoLimitTouchJump(al::HitSensor *,al::HitSensor *);
    bool sendMsgNoticePlayerDamage(al::HitSensor *,al::HitSensor *);
    bool sendMsgStatueDrop(al::HitSensor *,al::HitSensor *);
    bool sendMsgStatueTrampleReflect(al::HitSensor *,al::HitSensor *);
    bool sendMsgStatuePush(al::HitSensor *,al::HitSensor *);
    bool sendMsgStatueSnap(al::HitSensor *,al::HitSensor *);
    bool sendMsgHitGrowFlowerPot(al::HitSensor *,al::HitSensor *);
    bool sendMsgHitGrowPlantPot(al::HitSensor *,al::HitSensor *);
    bool sendMsgImplantGrowFlowerSeed(al::HitSensor *,al::HitSensor *);
    bool sendMsgIcicleAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgIgnoreMirrorWarp(al::HitSensor *,al::HitSensor *);
    bool sendMsgIgnoredByRunawayNpc(al::HitSensor *,al::HitSensor *);
    bool sendMsgIgnorePushMotorcycle(al::HitSensor *,al::HitSensor *);
    bool sendMsgSandSharkAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgSeedAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgSeedAttackBig(al::HitSensor *,al::HitSensor *);
    bool sendMsgSeedAttackHold(al::HitSensor *,al::HitSensor *);
    bool sendMsgSeedItemGet(al::HitSensor *,al::HitSensor *);
    bool sendMsgSeedReflect(al::HitSensor *,al::HitSensor *);
    bool sendMsgSenobiTrample(al::HitSensor *,al::HitSensor *);
    bool sendMsgSenobiCancelStretch(al::HitSensor *,al::HitSensor *);
    bool sendMsgSenobiPunchBlockTransparent(al::HitSensor *,al::HitSensor *);
    bool sendMsgShibakenApproach(al::HitSensor *,al::HitSensor *);
    bool sendMsgShibakenKick(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackUpperPunch(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackObjUpperPunch(al::HitSensor *,al::HitSensor *);
    bool sendMsgShineGet(al::HitSensor *,al::HitSensor *);
    bool sendMsgShineGet2D(al::HitSensor *,al::HitSensor *);
    bool sendMsgSpherePush(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,float);
    bool sendMsgSphinxJumpAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgSphinxQuizRouteKill(al::HitSensor *,al::HitSensor *);
    bool sendMsgSphinxRideAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgSphinxRideAttackReflect(al::HitSensor *,al::HitSensor *);
    bool sendMsgPechoSpot(al::HitSensor *,al::HitSensor *);
    bool sendMsgBelowObjBroken(al::HitSensor *,al::HitSensor *);
    bool sendMsgBindCollidedGround(al::HitSensor *,al::HitSensor *);
    bool sendMsgBindKeepDemoStart(al::HitSensor *,al::HitSensor *);
    bool sendMsgBindKeepDemoExecute(al::HitSensor *,al::HitSensor *);
    bool sendMsgBindKeepDemoEnd(al::HitSensor *,al::HitSensor *);
    bool sendMsgBindRecoveryLife(al::HitSensor *,al::HitSensor *);
    bool sendMsgMayorItemReflect(al::HitSensor *,al::HitSensor *);
    bool sendMsgMayorItemCollide(al::HitSensor *,al::HitSensor *);
    bool sendMsgBlowObjAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgBlowObjAttackReflect(al::HitSensor *,al::HitSensor *);
    bool sendMsgConfirmFrailBox(al::HitSensor *,al::HitSensor *);
    bool sendMsgConfirmBrokenFrailBox(al::HitSensor *,al::HitSensor *);
    bool sendMsgTankLookOn(al::HitSensor *,al::HitSensor *);
    bool sendMsgTankKickHack(al::HitSensor *,al::HitSensor *);
    bool sendMsgTankKickEnemy(al::HitSensor *,al::HitSensor *);
    bool sendMsgTankBullet(al::HitSensor *,al::HitSensor *);
    bool sendMsgTankBulletNoReaction(al::HitSensor *,al::HitSensor *);
    bool sendMsgTimerAthleticDemoStart(al::LiveActor *);
    bool sendMsgRideOnStart(al::HitSensor *,al::HitSensor *);
    bool sendMsgRideOnEnd(al::HitSensor *,al::HitSensor *);
    bool sendMsgRideOnRelease(al::HitSensor *,al::HitSensor *);
    bool sendMsgHipDropTransformTransform(al::HitSensor *,al::HitSensor *);
    bool sendMsgHipDropTransformReverse(al::HitSensor *,al::HitSensor *);
    bool sendMsgHipDropTransformingUp(al::HitSensor *,al::HitSensor *);
    bool sendMsgHipDropTransformingDown(al::HitSensor *,al::HitSensor *);
    bool sendMsgHipDropTransformingFinish(al::HitSensor *,al::HitSensor *);
    bool sendMsgClearFire(al::HitSensor *,al::HitSensor *);
    bool sendMsgCollectAnimalTouchCollide(al::HitSensor *,al::HitSensor *);
    bool sendMsgBossKnuckleCounter(al::HitSensor *,al::HitSensor *);
    bool sendMsgBossKnuckleFallAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgBossKnuckleHackAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgBossKnuckleKillerAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgBossKnuckleIceConflict(al::HitSensor *,al::HitSensor *);
    bool sendMsgBossKnuckleIceFallToMummy(al::HitSensor *,al::HitSensor *);
    bool sendMsgSkaterAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgEnableInSaucePan(al::HitSensor *,al::HitSensor *);
    bool sendMsgEnableMapCheckPointWarp(al::HitSensor *,al::HitSensor *);
    bool sendMsgStartInSaucePan(al::HitSensor *,al::HitSensor *,bool);
    bool sendMsgEndInSaucePan(al::HitSensor *,al::HitSensor *);
    bool sendMsgLineDancerLink(al::HitSensor *,al::HitSensor *);
    bool sendMsgLongPushSensorHit(al::HitSensor *,al::HitSensor *);
    bool sendMsgLongPushBoxHit(al::HitSensor *,al::HitSensor *);
    bool sendMsgGoldHammerAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgTrashBoxIn(al::HitSensor *,al::HitSensor *);
    bool sendMsgTouchDoorDrumn(al::HitSensor *,al::HitSensor *);
    bool sendMsgKuribo2DTouch(al::HitSensor *,al::HitSensor *);
    bool sendMsgKuriboCollisionDamage(al::HitSensor *,al::HitSensor *);
    bool sendMsgKuriboCollisionKill(al::HitSensor *,al::HitSensor *);
    bool sendMsgKuriboFlick(al::HitSensor *,al::HitSensor *);
    bool sendMsgKuriboTowerOn(al::HitSensor *,al::HitSensor *,uint);
    bool sendMsgPartyPopperSoundAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgYokinBallAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgYoshiDirectEat(al::HitSensor *,al::HitSensor *);
    bool sendMsgYoshiTongueAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgYoshiTongueEatBind(al::HitSensor *,al::HitSensor *,float *,float *,float *);
    bool sendMsgYoshiTongueEatBindCancel(al::HitSensor *,al::HitSensor *);
    bool sendMsgYoshiTongueEatBindFinish(al::HitSensor *,al::HitSensor *);
    bool sendMsgYoshiTongueEatHomingTarget(al::HitSensor *,al::HitSensor *);
    bool sendMsgYukimaruPush(al::HitSensor *,al::HitSensor *);
    bool sendMsgPunchMachinePunchStraight(al::HitSensor *,al::HitSensor *);
    bool sendMsgPunchMachinePunchHook(al::HitSensor *,al::HitSensor *);
    bool sendMsgPunchMachinePunchUpper(al::HitSensor *,al::HitSensor *);
    bool sendMsgMorningStarWarpStart(al::HitSensor *,al::HitSensor *);
    bool sendMsgMorningStarWarpEnd(al::HitSensor *,al::HitSensor *);
    bool sendMsgGemyAim(al::HitSensor *,al::HitSensor *);
    bool sendMsgHammerBrosHammerEnemyAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgHammerBrosHammerHackAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgHammerBrosHammerSearch(al::HitSensor *,al::HitSensor *);
    bool sendMsgHackBrosContact(al::HitSensor *,al::HitSensor *);
    bool sendMsgMotorcycleAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgMotorcycleCollideParkingLot(al::HitSensor *,al::HitSensor *);
    bool sendMsgMotorcycleDashAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgMotorcycleDashCollide(al::HitSensor *,al::HitSensor *);
    bool sendMsgWanwanEnemyAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgWanwanPush(al::HitSensor *,al::HitSensor *);
    bool sendMsgWanwanReboundAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgWanwanBlockAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgWanwanHoleIn(al::HitSensor *,al::HitSensor *);
    bool sendMsgWaterRoadIn(al::HitSensor *,al::HitSensor *);
    bool sendMsgWaterRoadNear(al::HitSensor *,al::HitSensor *);
    bool sendMsgBreedaSlap(al::HitSensor *,al::HitSensor *);
    bool sendMsgBreedaPush(al::HitSensor *,al::HitSensor *);
    bool sendMsgGamaneBullet(al::HitSensor *,al::HitSensor *);
    bool sendMsgGamaneBulletThrough(al::HitSensor *,al::HitSensor *);
    bool sendMsgGamaneBulletForCoinFlower(al::HitSensor *,al::HitSensor *);
    bool sendMsgVolleyballNpcScareByEnemy(al::HitSensor *,al::HitSensor *);
    bool sendMsgRocketFlowerExtension(al::HitSensor *,al::HitSensor *);
    bool sendMsgWanderBossCameraRange(al::HitSensor *,al::HitSensor *);
    bool sendMsgKuriboGirlAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgKuriboGirlLove(al::HitSensor *,al::HitSensor *);
    bool sendMsgKuriboTop(al::HitSensor *,al::HitSensor *);
    bool sendMsgTRexAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgTRexAttackCollideBody(al::HitSensor *,al::HitSensor *);
    bool sendMsgTRexAttackCollideHead(al::HitSensor *,al::HitSensor *);
    bool sendMsgTRexDashAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgTRexScrollPartsBreakWith(al::HitSensor *,al::HitSensor *);
    bool sendMsgTsukkunNoTrace(al::HitSensor *,al::HitSensor *);
    bool sendMsgTouchFireDrum2D(al::HitSensor *,al::HitSensor *);
    bool sendMsgPropellerAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgTankExplosion(al::HitSensor *,al::HitSensor *);
    bool sendMsgTankHackTrample(al::HitSensor *,al::HitSensor *);
    bool sendMsgUtsuboAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgKillerAttackNoExplode(al::HitSensor *,al::HitSensor *);
    bool sendMsgKillerMagnumAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgKillerMagnumHackAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgGabuzouAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgStackerRollingAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgStackerCapBoostAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgIgnoreIgnitionBomb(al::HitSensor *,al::HitSensor *);
    bool sendMsgExplosionReflectBomb(al::HitSensor *,al::HitSensor *);
    bool sendMsgGolemStampPress(al::HitSensor *,al::HitSensor *);
    bool sendMsgSwitchOnWithSaveRequest(al::LiveActor *,SaveObjInfo *);
    bool sendMsgWanwanReboundAttackToCollided(al::LiveActor const*,al::HitSensor *);
    bool sendMsgWanwanBlockAttackToCollided(al::LiveActor const*,al::HitSensor *);
    bool sendMsgDigPointSmell(al::HitSensor *,al::HitSensor *,DigPoint *);
    bool sendMsgMofumofuBodyChainExplode(al::HitSensor *,al::HitSensor *,int);
    bool sendMsgMoonBasementRockThroughCollision(al::HitSensor *,al::HitSensor *,bool);
    bool sendMsgFishingWait(al::HitSensor *,al::HitSensor *,al::HitSensor *);
    bool sendMsgFishingUpImmediately(al::HitSensor *,al::HitSensor *,sead::Matrix34<float> const&,sead::Vector3<float> const&,char const*);
    bool sendMsgGunetterPush(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,float);
    bool sendMsgTestPunch(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,int,int);
    bool sendMsgTestPunchStrong(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,int,int);
    bool sendMsgPunchGuard(al::HitSensor *,al::HitSensor *,int,int);
    bool sendMsgTsukkunThrust(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,int,bool);
    bool sendMsgTsukkunThrustSpin(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,int,bool);
    bool sendMsgTsukkunThrustReflect(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,int,bool);
    bool sendMsgTsukkunThrustCollide(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,int,bool);
    bool sendMsgTsukkunThrustHitReflectCollide(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,int,bool);
    bool sendMsgTsukkunThrustReflectCollide(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,int,bool);
    bool sendMsgTsukkunThrustHole(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,sead::Vector3<float> const&);
    bool sendMsgTsukkunThroughCollide(al::HitSensor *,al::HitSensor *);
    bool sendMsgTsukkunHoldCollide(al::HitSensor *,al::HitSensor *);
    bool sendMsgTsukkunForceCancelCollide(al::HitSensor *,al::HitSensor *);
    bool sendMsgNetworkShootingShot(al::HitSensor *,al::HitSensor *,int);
    bool sendMsgNetworkShootingChargeShot(al::HitSensor *,al::HitSensor *,int);
    bool sendMsgRequestPlayerJumpBreakFloor(al::HitSensor *,al::HitSensor *);
    bool sendMsgRequestPlayerJump(al::HitSensor *,al::HitSensor *,float);
    bool sendMsgRequestPlayerTrampleJump(al::HitSensor *,al::HitSensor *,float);
    bool sendMsgRequestPlayerSpinJump(al::HitSensor *,al::HitSensor *,float);
    bool sendMsgRequestSphinxJump(al::HitSensor *,al::HitSensor *,float);
    bool sendMsgIgnoreTouchTarget(al::HitSensor *,al::HitSensor *);
    bool sendMsgIgnoreTouchTarget(al::ScreenPointer *,al::ScreenPointTarget *);
    bool sendMsgInitTouchTargetInfo(al::HitSensor *,al::HitSensor *,TouchTargetInfo *,sead::Vector3<float> const*);
    bool sendMsgInitTouchTargetInfo(al::ScreenPointer *,al::ScreenPointTarget *,TouchTargetInfo *,sead::Vector3<float> const*);
    bool sendMsgCollisionImpulse(al::HitSensor *,al::HitSensor *,sead::Vector3<float> *,sead::Vector3<float> const&,float,sead::Vector3<float> const&,float);
    bool sendMsgWhipHold(al::HitSensor *,al::HitSensor *,WhipTargetInfo *);
    bool sendMsgWhipBind(al::HitSensor *,al::HitSensor *,WhipTargetInfo *);
    bool sendMsgWhipThrow(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&);
    bool sendMsgMagnet(al::HitSensor *,al::HitSensor *,bool);
    bool sendMsgMagnetBulletAttack(al::HitSensor *,al::HitSensor *,float);
    bool sendMsgDashPanel(al::HitSensor *,al::HitSensor *,int);
    bool sendMsgTrampolineCrackJump(al::HitSensor *,al::HitSensor *,float,float);
    bool sendMsgCapTouchWall(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,sead::Vector3<float> const&);
    bool sendMsgCapRethrow(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,sead::Vector3<float> const&,sead::Vector3<float> const&);
    bool sendMsgCapRethrowReturnOnly(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,sead::Vector3<float> const&,sead::Vector3<float> const&);
    bool sendMsgCapChangeGiant(al::HitSensor *,al::HitSensor *,float,int);
    bool sendMsgPackunEatCancel(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,sead::Vector3<float> const&);
    bool sendMsgPackunEatEnd(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,sead::Vector3<float> const&);
    bool sendMsgPackunEatStartFollow(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const*);
    bool sendMsgFireBlowerAttack(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,sead::Vector3<float> const&,float);
    //bool sendMsgPaint(al::HitSensor *,al::HitSensor *,sead::Color4u8 const&,int,int);
    bool sendMsgPaintTexture(al::HitSensor *,al::HitSensor *,int,float,int);
    //bool sendMsgCheckPaintClear(al::HitSensor *,al::HitSensor *,sead::Color4u8 const&,sead::Vector3<float> const&,int);
    bool sendMsgCheckPaintAlpha(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&);
    bool sendMsgByugoBlow(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&);
    bool sendMsgHackDirectStageInit(al::HitSensor *,al::HitSensor *,IUsePlayerHack *);
    bool sendMsgObjSnapForce(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&);
    bool sendMsgCapBeamerBeam(al::HitSensor *,al::HitSensor *);
    bool sendMsgHosuiAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgHosuiAttackCollide(al::HitSensor *,al::HitSensor *);
    bool sendMsgHosuiAttackNoEffect(al::HitSensor *,al::HitSensor *);
    bool sendMsgHosuiAttackStrong(al::HitSensor *,al::HitSensor *);
    bool sendMsgHosuiTouch(al::HitSensor *,al::HitSensor *);
    bool sendMsgHosuiTrample(al::HitSensor *,al::HitSensor *);
    bool sendMsgHosuiTrampleReflect(al::HitSensor *,al::HitSensor *);
    bool sendMsgHosuiTrampleReflectHigh(al::HitSensor *,al::HitSensor *);
    bool sendMsgBubbleAttack(al::HitSensor *,al::HitSensor *);
    bool sendMsgBubbleAttackToPecho(al::HitSensor *,al::HitSensor *);
    bool sendMsgBubbleReflectH(al::HitSensor *,al::HitSensor *);
    bool sendMsgBubbleReflectV(al::HitSensor *,al::HitSensor *);
    bool sendMsgBubbleWallTouch(al::HitSensor *,al::HitSensor *);
    bool sendMsgBubbleGroundTouchTrigger(al::HitSensor *,al::HitSensor *);
    bool sendMsgBubbleLauncherStart(al::HitSensor *,al::HitSensor *);
    bool sendMsgSenobiPartsMove(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,float);
    bool sendMsgStampTo2D(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&);
    bool sendMsgAirExplosion(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&);
    bool sendMsgPushVelocity(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&);
    bool sendMsgGhostRecordStartOk(al::HitSensor *,al::HitSensor *,char const*);
    bool sendMsgSandGeyserRaise(al::HitSensor *,al::HitSensor *,float,float);
    bool sendMsgRaceWait(al::LiveActor *);
    bool sendMsgRaceStart(al::LiveActor *);
    bool sendMsgRaceStop(al::LiveActor *);
    bool sendMsgRaceReturnToCourse(al::LiveActor *,sead::Vector3<float> const&,sead::Vector3<float> const&);
    bool sendMsgPlayerLookAtPosition(al::HitSensor *,al::HitSensor *,sead::Vector3<float> *);
    bool sendMsgTargetMarkerPosition(al::HitSensor *,al::HitSensor *,sead::Vector3<float> *);
    bool sendMsgHackBlowJump(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,float);
    bool sendMsgGolemStampPushV(al::HitSensor *,al::HitSensor *,float);
    bool sendMsgGolemStampPushH(al::HitSensor *,al::HitSensor *,float);
    bool sendMsgRequestPlayerWaitAnimDigPoint(al::HitSensor *,al::HitSensor *);
    bool sendMsgEventFlowScareCheck(al::HitSensor *,al::HitSensor *,al::EventFlowExecutor *);
    bool sendMsgPlayerItemGetAll(al::HitSensor *,al::HitSensor *);
    bool sendMsgPlayerItemGetAll2D(al::HitSensor *,al::HitSensor *);
    bool sendMsgTRexAttackAll(al::HitSensor *,al::HitSensor *);
    bool sendMsgSeedTouch(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,sead::Vector3<float> const&);
    bool sendMsgSphinxRideAttackTouchThrough(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,sead::Vector3<float> const&);
    bool sendMsgSphinxRideAttackTouch(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&,sead::Vector3<float> const&);
    bool sendMsgBlockUpperPunch2D(al::HitSensor *,al::HitSensor *);
    bool sendMsgGotogotonOn(al::HitSensor *,al::HitSensor *);
    bool sendMsgGotogotonGetJumpPath(al::HitSensor *,al::HitSensor *,al::ParabolicPath *);
    bool sendMsgGotogotonGoalExist(al::HitSensor *,al::HitSensor *);
    bool sendMsgGotogotonGoalMatch(al::HitSensor *,al::HitSensor *,GotogotonMark const*);
    bool sendMsgBossMagmaBreathForce(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&);
    bool sendMsgBossMagmaCatchPlayer(al::HitSensor *,al::HitSensor *);
    bool sendMsgBossMagmaReleasePlayer(al::HitSensor *,al::HitSensor *);
    bool sendMsgBossMagmaDeadDemoStart(al::HitSensor *,al::HitSensor *);
    bool sendMsgBossMagmaDeadDemoEnd(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&);
    bool sendMsgBossMagmaResetPos(al::HitSensor *,al::HitSensor *,sead::Vector3<float> const&);
    bool sendMsgBossMagmaQueryToBubble(al::HitSensor *,al::HitSensor *);
    bool sendMsgCheckFishingTarget(al::HitSensor *,al::HitSensor *,FishingFish const*);
    bool sendMsgPushToPlayerAndKillVelocityToTarget(al::LiveActor *,al::HitSensor *,al::HitSensor *);
    bool sendMsgPushToPlayerAndKillVelocityToTargetH(al::LiveActor *,al::HitSensor *,al::HitSensor *);
    bool sendMsgInitCapTarget(al::HitSensor *,al::HitSensor *,CapTargetInfo const**);
    bool sendMsgTransferHack(al::HitSensor *,al::HitSensor *);
    bool sendMsgRequestTransferHack(al::HitSensor *,al::HitSensor *);
    bool sendMsgInitHack(al::HitSensor *,al::HitSensor *);
    bool sendMsgEndHack(al::HitSensor *,al::HitSensor *,HackEndParam const*);
    bool sendMsgNpcScareByEnemy(al::HitSensor *,al::HitSensor *,int);

} // namespace rs
