name: CMake Compile Test
on:
  push:
    branches:
    - stable
    - dev
  pull_request:
    branches:
    - stable
    - dev
  workflow_dispatch:
  
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  Compile:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    
    # Use a container with Devkitpro already setup
    container: pixelkiri/devkitpro-alpine-switch:latest
    steps:
    - name: Setup Checkout and Submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.26.x'
    
    - name: Build LunaKit
      run: cmake -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain.cmake -S . -B build && make -C build subsdk9_meta -j4
